/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Versa itemized receipt
 */
export interface Receipt {
  version: string;
  header: {
    receipt_id: string;
    /**
     * ISO 4217 currency code
     */
    currency: "usd" | "eur" | "jpy" | "gbp" | "aud" | "cad" | "chf" | "cnh";
    amount: number;
    subtotal?: number;
    created_at: number;
    mcc: string | null;
    third_party: {
      first_party_relation:
        | "bnpl"
        | "delivery_service"
        | "marketplace"
        | "payment_processor"
        | "platform"
        | "point_of_sale";
      /**
       * Determines whether the merchant or third party gets top billing on the receipt
       */
      make_primary: boolean;
      merchant: Merchant;
    } | null;
    customer: {
      name: string;
      email: string | null;
      address: null | Address;
      phone: string | null;
      [k: string]: unknown;
    } | null;
    location: null | Place;
  };
  itemization:
    | {
        general?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }
    | {
        lodging?: {
          /**
           * @minItems 1
           */
          lodging_items: [
            {
              check_in: number;
              check_out: number;
              location: Place;
              /**
               * @minItems 1
               */
              items: [Item, ...Item[]];
              room?: null | string;
              guests?: null | string;
              metadata?: null | [ItemMetadata, ...ItemMetadata[]];
              [k: string]: unknown;
            },
            ...{
              check_in: number;
              check_out: number;
              location: Place;
              /**
               * @minItems 1
               */
              items: [Item, ...Item[]];
              room?: null | string;
              guests?: null | string;
              metadata?: null | [ItemMetadata, ...ItemMetadata[]];
              [k: string]: unknown;
            }[]
          ];
          invoice_level_discounts: null | [Discount, ...Discount[]];
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }
    | {
        ecommerce?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }
    | {
        car_rental?: {
          rental_time: number;
          return_time: number;
          rental_location: Place;
          return_location: Place;
          vehicle_desscription: string;
          driver_name: string;
          odometer_reading_in: number;
          odometer_reading_out: number;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }
    | {
        transit_route?: {
          departure_address?: null | Address;
          arrival_address?: null | Address;
          departure_time?: number;
          arrival_time?: number;
          polyline?: null | string;
          taxes?: null | [Tax, ...Tax[]];
          invoice_level_discounts?: null | [Discount, ...Discount[]];
          metadata?: null | [ItemMetadata, ...ItemMetadata[]];
          tip?: number | null;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }
    | {
        subscription?: {
          /**
           * @minItems 1
           */
          subscription_items: [
            {
              subscription_type: "one_time" | "recurring";
              description: string;
              interval: null | ("day" | "week" | "month" | "year");
              interval_count: number | null;
              current_period_start: number | null;
              current_period_end: number | null;
              quantity: number | null;
              unit_cost: number | null;
              taxes: null | [Tax, ...Tax[]];
              metadata: null | [ItemMetadata, ...ItemMetadata[]];
              discounts: null | [Discount, ...Discount[]];
              [k: string]: unknown;
            },
            ...{
              subscription_type: "one_time" | "recurring";
              description: string;
              interval: null | ("day" | "week" | "month" | "year");
              interval_count: number | null;
              current_period_start: number | null;
              current_period_end: number | null;
              quantity: number | null;
              unit_cost: number | null;
              taxes: null | [Tax, ...Tax[]];
              metadata: null | [ItemMetadata, ...ItemMetadata[]];
              discounts: null | [Discount, ...Discount[]];
              [k: string]: unknown;
            }[]
          ];
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }
    | {
        flight?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
  actions:
    | null
    | {
        name: string;
        url: string;
        [k: string]: unknown;
      }[];
  payment: null | {
    [k: string]: unknown;
  };
}
export interface Merchant {
  name: string;
  /**
   * Hex color
   */
  brand_color: string;
  logo: string | null;
  website: string | null;
  [k: string]: unknown;
}
export interface Address {
  street_address: string | null;
  city: string | null;
  region: string | null;
  country: string;
  postal_code: string | null;
  lat: number;
  lon: number;
  [k: string]: unknown;
}
export interface Place {
  name: string | null;
  address: null | Address;
  phone: string | null;
  url: null | string;
  google_place_id: string | null;
  image: null | string;
  [k: string]: unknown;
}
export interface Item {
  description: string;
  total: number;
  quantity?: null | number;
  uniit_cost?: null | number;
  unit?: null | string;
  taxes?: null | [Tax, ...Tax[]];
  metadata?: null | [ItemMetadata, ...ItemMetadata[]];
  product_image?: null | string;
  group?: null | string;
  url?: null | string;
  discounts?: null | [Discount, ...Discount[]];
  [k: string]: unknown;
}
export interface Tax {
  amount: number;
  rate: number | null;
  name: string;
  [k: string]: unknown;
}
export interface ItemMetadata {
  metadata_type: "sku" | "unspsc" | "asin" | "other";
  name: string;
  value: string;
  [k: string]: unknown;
}
export interface Discount {
  amount: number;
  name: string;
  discount_type: "fixed" | "percentage";
  [k: string]: unknown;
}
